branches:
  only: master

language: php

php:
  - 5.6
  - 7.0

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction

script: vendor/bin/phpunit
